import type { Metadata } from "next";
import { Rosarivo, Tinos } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const vivoSans = localfont({
  src: [
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Thin.ttf",
      weight: "100",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Extralight.ttf",
      weight: "200",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Light.ttf",
      weight: "300",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Demibold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Extrabold.ttf",
      weight: "800",
    },
    {
      path: "../../public/fonts/vivosans/vivoSansGlobal-Heavy.ttf",
      weight: "900",
    },
  ],
  variable: "--font-vivo-sans",
});

const rosarivo = Rosarivo({
  variable: "--font-rosarivo",
  subsets: ["latin"],
  weight: "400",
});

const tinos = Tinos({
  variable: "--font-tinos",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rosarivo.variable} ${tinos.variable} ${vivoSans.variable} antialiased no-select`}
      >
        {children}
      </body>
    </html>
  );
}
